version: "2.1"

networks:
  public:

services:
  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-public
    expose:
      - 4004
    ports:
      - 4004:4004
    command: |
      bash -c "
        ls -al /etc/sawtooth/keys
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        echo 'start' &&
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
    volumes:
      - ./sawtooth_data:/var/lib/sawtooth
    networks:
      - public

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-public
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004
    networks:
      - public

  rest.api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-public
    environment:
      - VIRTUAL_HOST=rest.api
    expose:
      - 8008
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest.api:8008
    networks:
      - public

  sawtooth-tfa-sc-tp-go-kaztel:
    image: $ALLATRACK_DOCKER_ID/sawtooth-tfa-sc-tp-go
    container_name: sawtooth-tfa-sc-tp-go-kaztel
    depends_on:
      - validator
      - rest.api
    entrypoint: tfa-service-client-tp-go --connect=tcp://validator:4004 --family=kaztel --version=0.1
    networks:
      - public

  sawtooth-tfa-sc-tp-go-egov:
    image: $ALLATRACK_DOCKER_ID/sawtooth-tfa-sc-tp-go
    container_name: sawtooth-tfa-sc-tp-g-egov
    depends_on:
      - validator
      - rest.api
    entrypoint: tfa-service-client-tp-go --connect=tcp://validator:4004 --family=egov --version=0.1
    networks:
      - public

  sawtooth-tfa-s-tp-go:
    image: $ALLATRACK_DOCKER_ID/sawtooth-tfa-s-tp-go
    container_name: sawtooth-tfa-s-tp-go
    depends_on:
      - validator
      - rest.api
    entrypoint: tfa-service-tp-go --connect=tcp://validator:4004 --family=tfa --version=0.1
    networks:
      - public

  sawtooth-tfa-entrance-backend:
    container_name: sawtooth-tfa-entrance-backend
    image: sawtooth-tfa-entrance-backend
    depends_on:
      - rest.api
      - validator
      - mongo
      - redis
    environment:
      - PORT=443
      - NODE_ENV=local
      - APP_PATH=/home/peshkov/dev/blockchain/hyperledger/blockchain-2fa-backend
      - LOG_PATH=/home/peshkov/dev/blockchain/hyperledger/blockchain-2fa-backend/logs
      - API_KEY=$API_KEY
      - API_KEY_FRONTEND=sgdfhdmgdkfgjk
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMS_USERNAME=2authorization
      - SMS_PASSWORD=sHg0IBRFrd4j7Pc
      - SMS_CALLBACK_TOKEN=r6eRWSC8UgWb
      - KAZAHTELECOM_KEY=52d4f2d54f254
      - GOOGLE_API_KEY=AIzaSyDR4G506UdebphK1mnMxv4eqTDpu_5JuiY
      - FIREBASE_CLOUD_KEY=AAAANnj9ZGc:APA91bGkV3mkrIUZb6eK6rTGcN66edPymuMp5N3W0ebY9F0DdnOLfghhTFh44YYwe8YuaBMsEzBWoA-LHIwSgT6F6TpOkW2UBFxsoblSZiw7ugozjE8esnH1-m9IOzFmQeZTQhTE5nhw
      - FIREBASE_CLOUD_ID=233958106215
      - TFA_FAMILY_NAME=tfa
      - TFA_FAMILY_VERSION=0.1
      - KAZTEL_FAMILY_NAME=kaztel
      - KAZTEL_FAMILY_VERSION=0.1
      - EGOV_FAMILY_NAME=egov
      - EGOV_FAMILY_VERSION=0.1
      - VALIDATOR_REST_API=http://nginx/sawtooth
      - VALIDATOR_REST_API_WS=nginx/sawtooth-ws
      - VALIDATOR_REST_API_USER=sammy
      - VALIDATOR_REST_API_PASS=11111111
      - FRONTEND_API=http://allatrack-tfa.tk/#
      - KAZTEL_CALLBACK_URL=http://localhost:8080/#
      - EGOV_CALLBACK_URL=http://localhost:8080/#
      - TELEGRAM_BOT_KEY=496129046:AAGMPrUnD2iOaoedbsWYBkUKL4t9UM0Wtzs
      - MONGO_DB=mongodb://mongo/telegram_alert
    networks:
      - public
    ports:
      - 443:443

  sawtooth-tfa-entrance-frontend:
    container_name: sawtooth-tfa-entrance-frontend
    image: sawtooth-tfa-entrance-frontend
    environment:
      - PORT=80
      - API_URL=https://allatrack-tfa.tk:443/v1/api
    networks:
      - public
    ports:
      - 80:80

  sawtooth-tfa-cabinet:
    container_name: sawtooth-tfa-cabinet
    image: sawtooth-tfa-cabinet
    environment:
      - API_URL_ENV=http://allatrack-tfa.tk:8080/
      - PORT=8080
      - VALIDATOR_REST_API_WS=nginx/sawtooth-ws
      - VALIDATOR_REST_API_HTTP=http://nginx/sawtooth
      - VALIDATOR_REST_API_HOST=nginx
      - VALIDATOR_REST_API_PORT=8008
      - VALIDATOR_REST_API_USER=sammy
      - VALIDATOR_REST_API_PASS=11111111
      - DATABASE=mongodb://mongo/twofa
      - AUTH_ADMIN_SECRET=yoursecret
      - USE_PROXY_SERVER=false
      - INIT_ROOT_ADMIN=true
      - ROOT_ADMIN_NAME=Root Administrator
      - ROOT_ADMIN_USERNAME=root
      - ROOT_ADMIN_EMAIL=root@tfa.kz
      - ROOT_ADMIN_PASS=dfghi5j0rtg
    depends_on:
      - rest.api
      - validator
      - mongo
    ports:
      - 3002:8080
    networks:
      - public

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - public

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - public

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - public

  redis:
    container_name: redis
    image: redis
    ports:
      - 6380:6379
    networks:
      - public
