// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_client.proto

/*
Package handler is a generated protocol buffer package.

It is generated from these files:
	service_client.proto

It has these top-level messages:
	Log
	User
	SCPayload
*/
package handler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PayloadType int32

const (
	PayloadType_USER_CREATE   PayloadType = 0
	PayloadType_USER_UPDATE   PayloadType = 1
	PayloadType_CODE_GENERATE PayloadType = 2
	PayloadType_CODE_VERIFY   PayloadType = 3
)

var PayloadType_name = map[int32]string{
	0: "USER_CREATE",
	1: "USER_UPDATE",
	2: "CODE_GENERATE",
	3: "CODE_VERIFY",
}
var PayloadType_value = map[string]int32{
	"USER_CREATE":   0,
	"USER_UPDATE":   1,
	"CODE_GENERATE": 2,
	"CODE_VERIFY":   3,
}

func (x PayloadType) String() string {
	return proto.EnumName(PayloadType_name, int32(x))
}
func (PayloadType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Log struct {
	Event      string  `protobuf:"bytes,1,opt,name=Event" json:"Event,omitempty"`
	Status     string  `protobuf:"bytes,2,opt,name=Status" json:"Status,omitempty"`
	Code       uint32  `protobuf:"varint,3,opt,name=Code" json:"Code,omitempty"`
	ExpiredAt  float64 `protobuf:"fixed64,4,opt,name=ExpiredAt" json:"ExpiredAt,omitempty"`
	Embeded    bool    `protobuf:"varint,5,opt,name=Embeded" json:"Embeded,omitempty"`
	ActionTime float64 `protobuf:"fixed64,6,opt,name=ActionTime" json:"ActionTime,omitempty"`
	Method     string  `protobuf:"bytes,7,opt,name=Method" json:"Method,omitempty"`
	Cert       string  `protobuf:"bytes,8,opt,name=Cert" json:"Cert,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Log) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Log) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Log) GetExpiredAt() float64 {
	if m != nil {
		return m.ExpiredAt
	}
	return 0
}

func (m *Log) GetEmbeded() bool {
	if m != nil {
		return m.Embeded
	}
	return false
}

func (m *Log) GetActionTime() float64 {
	if m != nil {
		return m.ActionTime
	}
	return 0
}

func (m *Log) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Log) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

type User struct {
	PhoneNumber    string  `protobuf:"bytes,1,opt,name=PhoneNumber" json:"PhoneNumber,omitempty"`
	Uin            uint32  `protobuf:"varint,2,opt,name=Uin" json:"Uin,omitempty"`
	Name           string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	IsVerified     bool    `protobuf:"varint,4,opt,name=IsVerified" json:"IsVerified,omitempty"`
	Email          string  `protobuf:"bytes,5,opt,name=Email" json:"Email,omitempty"`
	Sex            string  `protobuf:"bytes,6,opt,name=Sex" json:"Sex,omitempty"`
	Birthdate      float64 `protobuf:"fixed64,7,opt,name=Birthdate" json:"Birthdate,omitempty"`
	AdditionalData string  `protobuf:"bytes,8,opt,name=AdditionalData" json:"AdditionalData,omitempty"`
	Logs           []*Log  `protobuf:"bytes,9,rep,name=Logs" json:"Logs,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetUin() uint32 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *User) GetBirthdate() float64 {
	if m != nil {
		return m.Birthdate
	}
	return 0
}

func (m *User) GetAdditionalData() string {
	if m != nil {
		return m.AdditionalData
	}
	return ""
}

func (m *User) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type SCPayload struct {
	Action      PayloadType `protobuf:"varint,1,opt,name=Action,enum=PayloadType" json:"Action,omitempty"`
	PhoneNumber string      `protobuf:"bytes,2,opt,name=PhoneNumber" json:"PhoneNumber,omitempty"`
	PayloadUser *User       `protobuf:"bytes,3,opt,name=PayloadUser" json:"PayloadUser,omitempty"`
	PayloadLog  *Log        `protobuf:"bytes,4,opt,name=PayloadLog" json:"PayloadLog,omitempty"`
}

func (m *SCPayload) Reset()                    { *m = SCPayload{} }
func (m *SCPayload) String() string            { return proto.CompactTextString(m) }
func (*SCPayload) ProtoMessage()               {}
func (*SCPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SCPayload) GetAction() PayloadType {
	if m != nil {
		return m.Action
	}
	return PayloadType_USER_CREATE
}

func (m *SCPayload) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SCPayload) GetPayloadUser() *User {
	if m != nil {
		return m.PayloadUser
	}
	return nil
}

func (m *SCPayload) GetPayloadLog() *Log {
	if m != nil {
		return m.PayloadLog
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*SCPayload)(nil), "SCPayload")
	proto.RegisterEnum("PayloadType", PayloadType_name, PayloadType_value)
}

func init() { proto.RegisterFile("service_client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xa7, 0xfc, 0xf7, 0xc9, 0xd2, 0x65, 0xa2, 0x0c, 0x5d, 0x8c, 0x61, 0x42, 0xd9, 0xcc,
	0x2e, 0x72, 0x91, 0x3d, 0x41, 0x9a, 0x68, 0xa3, 0x90, 0x65, 0x41, 0x4e, 0x0a, 0xdb, 0x4d, 0x50,
	0xa2, 0xb3, 0x44, 0x60, 0x5b, 0xc1, 0x56, 0x4b, 0xfb, 0x3a, 0x7b, 0x9d, 0xbd, 0xcf, 0xae, 0x87,
	0x64, 0xb7, 0x35, 0xed, 0xdd, 0xf9, 0x7e, 0xc7, 0x3a, 0x7c, 0xdf, 0x87, 0xe1, 0xbc, 0xc0, 0xfc,
	0x56, 0xef, 0x71, 0xbb, 0x4f, 0x34, 0x66, 0x76, 0x7c, 0xca, 0x8d, 0x35, 0xa3, 0xbf, 0x04, 0x9a,
	0x0b, 0x73, 0xa0, 0xe7, 0xd0, 0xe6, 0xb7, 0x98, 0x59, 0x46, 0x42, 0x12, 0x05, 0xa2, 0x14, 0xf4,
	0x1d, 0x74, 0x62, 0x2b, 0xed, 0x4d, 0xc1, 0x1a, 0x1e, 0x57, 0x8a, 0x52, 0x68, 0xcd, 0x8c, 0x42,
	0xd6, 0x0c, 0x49, 0x34, 0x10, 0x7e, 0xa6, 0xef, 0x21, 0xe0, 0x77, 0x27, 0x9d, 0xa3, 0x9a, 0x5a,
	0xd6, 0x0a, 0x49, 0x44, 0xc4, 0x13, 0xa0, 0x0c, 0xba, 0x3c, 0xdd, 0xa1, 0x42, 0xc5, 0xda, 0x21,
	0x89, 0x7a, 0xe2, 0x41, 0xd2, 0x0f, 0x00, 0xd3, 0xbd, 0xd5, 0x26, 0x5b, 0xeb, 0x14, 0x59, 0xc7,
	0x3f, 0xac, 0x11, 0xe7, 0xe1, 0x3b, 0xda, 0xa3, 0x51, 0xac, 0x5b, 0x7a, 0x28, 0x95, 0xf7, 0x80,
	0xb9, 0x65, 0x3d, 0x4f, 0xfd, 0x3c, 0xfa, 0x47, 0xa0, 0xb5, 0x29, 0x30, 0xa7, 0x21, 0xf4, 0x57,
	0x47, 0x93, 0xe1, 0xf2, 0x26, 0xdd, 0x61, 0x5e, 0x85, 0xaa, 0x23, 0x3a, 0x84, 0xe6, 0x46, 0x67,
	0x3e, 0xd7, 0x40, 0xb8, 0xd1, 0x1d, 0x5c, 0xca, 0xb4, 0x0c, 0x15, 0x08, 0x3f, 0x3b, 0x73, 0x57,
	0xc5, 0x35, 0xe6, 0xfa, 0xb7, 0x46, 0xe5, 0x53, 0xf5, 0x44, 0x8d, 0xf8, 0xda, 0x52, 0xa9, 0x13,
	0x1f, 0xca, 0xd5, 0xe6, 0x84, 0xbb, 0x1d, 0xe3, 0x9d, 0xcf, 0x12, 0x08, 0x37, 0xba, 0x72, 0x2e,
	0x75, 0x6e, 0x8f, 0x4a, 0x5a, 0xf4, 0x39, 0x88, 0x78, 0x02, 0xf4, 0x23, 0x9c, 0x4d, 0x95, 0xd2,
	0x2e, 0xb2, 0x4c, 0xe6, 0xd2, 0xca, 0x2a, 0xd4, 0x33, 0x4a, 0x19, 0xb4, 0x16, 0xe6, 0x50, 0xb0,
	0x20, 0x6c, 0x46, 0xfd, 0x49, 0x6b, 0xbc, 0x30, 0x07, 0xe1, 0xc9, 0xe8, 0x0f, 0x81, 0x20, 0x9e,
	0xad, 0xe4, 0x7d, 0x62, 0xa4, 0xa2, 0x17, 0xd0, 0x29, 0x0b, 0xf4, 0xc1, 0xcf, 0x26, 0xaf, 0xc7,
	0xd5, 0x66, 0x7d, 0x7f, 0x42, 0x51, 0xed, 0x9e, 0x77, 0xd4, 0x78, 0xd9, 0xd1, 0x27, 0xe8, 0x57,
	0x0f, 0x5d, 0xa9, 0xbe, 0x98, 0xfe, 0xa4, 0x3d, 0x76, 0x42, 0xd4, 0x37, 0xf4, 0x02, 0xa0, 0x92,
	0x0b, 0x73, 0xf0, 0x35, 0x3d, 0xd8, 0xab, 0xf1, 0xcf, 0xf1, 0xe3, 0x39, 0xe7, 0x83, 0xbe, 0x81,
	0xfe, 0x26, 0xe6, 0x62, 0x3b, 0x13, 0x7c, 0xba, 0xe6, 0xc3, 0x57, 0x8f, 0x60, 0xb3, 0x9a, 0x3b,
	0x40, 0xe8, 0x5b, 0x18, 0xcc, 0x7e, 0xcc, 0xf9, 0xf6, 0x1b, 0x5f, 0x72, 0xe1, 0x50, 0xc3, 0x7d,
	0xe3, 0xd1, 0x35, 0x17, 0x57, 0x5f, 0x7f, 0x0e, 0x9b, 0x97, 0xc1, 0xaf, 0xee, 0x51, 0x66, 0x2a,
	0xc1, 0x7c, 0xd7, 0xf1, 0xbf, 0xf4, 0x97, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0x67, 0x7f,
	0xc9, 0xea, 0x02, 0x00, 0x00,
}
