apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: dockergen
  name: dockergen
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dockergen
    spec:
      containers:
      - args:
        - -notify-sighup
        - nginx
        - -watch
        - /etc/docker-gen/templates/nginx.tmpl
        - /etc/nginx/conf.d/default.conf
        image: jwilder/docker-gen
        name: dockergen
        resources: {}
        volumeMounts:
        - mountPath: /tmp/docker.sock
          name: dockergen-empty0
          readOnly: true
        - mountPath: /etc/docker-gen/templates/nginx.tmpl
          name: dockergen-empty1
        - mountPath: /etc/nginx/conf.d
          name: nginx-empty0
        - mountPath: /etc/nginx/.htpasswd
          name: nginx-empty1
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: dockergen-empty0
      - emptyDir: {}
        name: dockergen-empty1
      - emptyDir: {}
        name: nginx-empty0
      - emptyDir: {}
        name: nginx-empty1
status: {}
