apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
#      hostNetwork: true
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 82
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-empty0
        - mountPath: /etc/nginx/.htpasswd
          name: nginx-empty1
      restartPolicy: Always
      volumes:
      - name: nginx-empty0
        hostPath:
          path: /root/blockchain-2fa-net/networks/all/config/conf.d
      - name: nginx-empty1
        hostPath:
          path: /root/blockchain-2fa-net/networks/all/config/.htpasswd
status: {}
