apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sawtooth-tfa-entrance-backend
  name: sawtooth-tfa-entrance-backend
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: sawtooth-tfa-entrance-backend
status:
  loadBalancer: {}
