apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sawtooth-tfa-cabinet
  name: sawtooth-tfa-cabinet
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 8080
  selector:
    io.kompose.service: sawtooth-tfa-cabinet
status:
  loadBalancer: {}
