apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sawtooth-tfa-entrance-frontend
  name: sawtooth-tfa-entrance-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sawtooth-tfa-entrance-frontend
    spec:
      hostNetwork: true
      containers:
      - env:
#        - name: API_URL
#          value: http://localhost:443/v1/api
        - name: API_URL
          value: https://allatrack-tfa.tk:443/v1/api
        - name: PORT
          value: "80"
        image: allatrack/tfa-entrance-frontend
        name: tfa-entrance-frontend
        ports:
        - containerPort: 80
          hostPort: 80
        resources: {}
      restartPolicy: Always
status: {}
