apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: settings-tp
  name: settings-tp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: settings-tp
    spec:
      hostNetwork: true
      containers:
      - command:
        - settings-tp
        - -vv
        - -C
        - tcp://validator:4004
        image: hyperledger/sawtooth-settings-tp:1.0
        name: sawtooth-settings-tp-public
        resources: {}
      restartPolicy: Always
status: {}
