apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: validator
  name: validator
spec:
  ports:
  - name: "4004"
    port: 4004
    targetPort: 4004
  selector:
    io.kompose.service: validator
status:
  loadBalancer: {}
