apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-dev.yaml --emptyvols
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: validator
  name: validator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: validator
    spec:
      hostNetwork: true
      containers:
      - args:
        - bash
        - -c
        - "\n  ls -al /etc/sawtooth/keys\n  if [ ! -f /etc/sawtooth/keys/validator.priv
          ]; then\n  echo 'start' &&\n  sawadm keygen &&\n  sawtooth keygen my_key
          &&\n  sawset genesis -k /root/.sawtooth/keys/my_key.priv &&\n  sawadm genesis
          config-genesis.batch\n  fi;\n  sawtooth-validator -vv \n    --endpoint tcp://127.0.0.1:8800
          \n    --bind component:tcp://eth0:4004 \n    --bind network:tcp://eth0:8800\n"
        image: hyperledger/sawtooth-validator:1.0
        name: sawtooth-validator-public
        ports:
        - containerPort: 4004
        - containerPort: 8800
        resources: {}
        volumeMounts:
        - mountPath: /etc/sawtooth/config/poet-settings.sh
          name: validator-0-claim0
        - mountPath: /etc/sawtooth/config/simulator_rk_pub.pem
          name: validator-0-claim1
      volumes:
      - name: validator-0-claim1
        hostPath:
          path: /root/blockchain-2fa-net/networks/simulator_rk_pub.pem
      - name: validator-0-claim0
        hostPath:
          path: /root/blockchain-2fa-net/networks/poet-settings.sh
status: {}

