#!/usr/bin/env bash

# build projects
#echo 'build allatrack/tfa-entrance-backend image'
#cd ./../../blockchain-2fa-backend
#docker build -t allatrack/tfa-entrance-backend .
#
#echo 'build allatrack/tfa-entrance-frontend image'
#cd ./../../blockchain-2fa-frontend
#docker build -t allatrack/tfa-entrance-frontend .
#
#echo 'build allatrack/tfa-cabinet image'
#cd ./../../blockchain-2fa-web
#docker build -t allatrack/tfa-cabinet .
#
echo 'build allatrack/sawtooth-tfa-sc-tp-go bin programs'
cd ./..
docker run -v $(pwd)/bin:/project/sawtooth-core/bin \
           -v $(pwd)/sawtooth-core:/project/sawtooth-core \
           -v $(pwd)/go:/project/tfa/go \
           sawtooth-dev-go

echo 'build allatrack/sawtooth-tfa-sc-tp-go image image'
top_dir=$(cd $(dirname $(dirname $0)) && pwd)
export PATH=$PATH:$top_dir/go/bin
docker build -f docker/sawtooth-tfa-service-client-tp-go -t allatrack/sawtooth-tfa-sc-tp-go ./docker

echo 'build allatrack/sawtooth-tfa-sc-tp-go bin program'
cd ./..
docker run -v $(pwd)/bin:/project/sawtooth-core/bin \
           -v $(pwd)/sawtooth-core:/project/sawtooth-core \
           -v $(pwd)/go:/project/tfa/go \
           sawtooth-dev-go

echo 'build allatrack/sawtooth-tfa-sc-tp-go image image'
top_dir=$(cd $(dirname $(dirname $0)) && pwd)
export PATH=$PATH:$top_dir/go/bin
docker build -f docker/sawtooth-tfa-service-client-tp-go -t allatrack/sawtooth-tfa-sc-tp-go ./docker